apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader
  namespace: default
roleRef:
  apiGroup: ""
  kind: Role
  name: leader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
    apiGroup: ""
